import 'dart:math';
import 'package:flutter/material.dart';
import '../../../core/theme/app_theme.dart';

/// 全球化多语言社交社区 - 帖子列表页
/// 白皮书 2.3 节：创作者经济 (Prompt Economy) + 跨国技术交流论坛
class CommunityFeedPage extends StatefulWidget {
  const CommunityFeedPage({super.key});

  @override
  State<CommunityFeedPage> createState() => _CommunityFeedPageState();
}

class _CommunityFeedPageState extends State<CommunityFeedPage>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  final List<_CommunityPost> _posts = [];
  final Random _rng = Random(42);

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
    _generateMockPosts();
  }

  void _generateMockPosts() {
    final creators = [
      _Creator('NailArt_Tokyo', '东京美甲师', '🇯🇵', 12800),
      _Creator('CyberNails_Seoul', '赛博美甲', '🇰🇷', 9500),
      _Creator('InkBrush_Beijing', '水墨丹青', '🇨🇳', 15600),
      _Creator('ParisChic_Nails', '巴黎时尚', '🇫🇷', 21000),
      _Creator('NYC_GlossLab', '纽约光泽', '🇺🇸', 18700),
      _Creator('Berlin_NeonArt', '柏林霓虹', '🇩🇪', 8200),
      _Creator('Moscow_Gold', '莫斯科金箔', '🇷🇺', 6700),
      _Creator('Dubai_Lux', '迪拜奢华', '🇦🇪', 14300),
    ];

    final designs = [
      '赛博朋克霓虹渐变',
      '水墨蝴蝶翅膀纹理',
      '法式极简金边',
      '星空银河漩涡',
      '3D立体花卉',
      '金属液态质感',
      '日系樱花渐变',
      '哥特暗黑蕾丝',
    ];

    for (int i = 0; i < 20; i++) {
      final creator = creators[i % creators.length];
      _posts.add(_CommunityPost(
        id: 'post_$i',
        creator: creator,
        title: designs[i % designs.length],
        description: '基于 nanobanana 3.0 生成的 ${designs[i % designs.length]}设计，'
            '已适配5种甲型，打印分辨率 1200 DPI。Prompt 已上架交易市场。',
        likes: 100 + _rng.nextInt(5000),
        comments: 5 + _rng.nextInt(200),
        prints: 10 + _rng.nextInt(1000),
        promptPrice: _rng.nextBool() ? (0.99 + _rng.nextDouble() * 9.0) : null,
        tags: [
          designs[i % designs.length],
          creator.country,
          'nanobanana 3.0',
        ],
        translations: _generateTranslations(),
        timestamp: DateTime.now()
            .subtract(Duration(hours: _rng.nextInt(72))),
      ));
    }
  }

  Map<String, String> _generateTranslations() {
    return {
      'zh': '基于 nanobanana 3.0 生成的原创美甲设计',
      'en': 'Original nail design generated by nanobanana 3.0',
      'ja': 'nanobanana 3.0が生成したオリジナルネイルデザイン',
      'ko': 'nanobanana 3.0으로 생성된 오리지널 네일 디자인',
      'fr': 'Design d\'ongle original généré par nanobanana 3.0',
    };
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.bgDeepDark,
      appBar: AppBar(
        title: ShaderMask(
          shaderCallback: (bounds) =>
              AppTheme.gradientPurple.createShader(bounds),
          child: const Text(
            '全球创作者社区',
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.w700,
              fontFamily: 'CyberNeon',
              color: Colors.white,
              letterSpacing: 2,
            ),
          ),
        ),
        backgroundColor: AppTheme.bgDeepDark,
        actions: [
          // 发布按钮
          IconButton(
            icon: Container(
              padding: const EdgeInsets.all(6),
              decoration: BoxDecoration(
                gradient: AppTheme.gradientNeon,
                borderRadius: BorderRadius.circular(10),
              ),
              child: const Icon(
                Icons.add,
                color: AppTheme.bgDeepDark,
                size: 20,
              ),
            ),
            onPressed: () {
              // Navigator.pushNamed(context, '/community/publish');
            },
          ),
          const SizedBox(width: 8),
        ],
        bottom: TabBar(
          controller: _tabController,
          indicatorColor: AppTheme.primaryNeonGreen,
          labelColor: AppTheme.primaryNeonGreen,
          unselectedLabelColor: AppTheme.textHint,
          tabs: const [
            Tab(text: '🔥 热门'),
            Tab(text: '💰 Prompt 市场'),
            Tab(text: '🌍 全球'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _buildFeedTab(),
          _buildPromptMarketTab(),
          _buildGlobalTab(),
        ],
      ),
    );
  }

  Widget _buildFeedTab() {
    return RefreshIndicator(
      color: AppTheme.primaryNeonGreen,
      onRefresh: () async {
        await Future.delayed(const Duration(seconds: 1));
      },
      child: ListView.builder(
        padding: const EdgeInsets.only(top: 8, bottom: 80),
        itemCount: _posts.length,
        itemBuilder: (context, index) => _PostCard(post: _posts[index]),
      ),
    );
  }

  Widget _buildPromptMarketTab() {
    final promptPosts = _posts.where((p) => p.promptPrice != null).toList();
    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: promptPosts.length,
      itemBuilder: (context, index) {
        final post = promptPosts[index];
        return _PromptMarketCard(post: post);
      },
    );
  }

  Widget _buildGlobalTab() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          // 全球地图示意
          Container(
            width: 200,
            height: 200,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: AppTheme.gradientOcean,
              boxShadow: [
                BoxShadow(
                  color: AppTheme.accentNeonCyan.withOpacity(0.3),
                  blurRadius: 30,
                ),
              ],
            ),
            child: const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.public, size: 48, color: Colors.white),
                  SizedBox(height: 8),
                  Text(
                    '13+ Languages',
                    style: TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.w700,
                      fontSize: 16,
                    ),
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(height: 24),
          Text(
            'AI 实时翻译 · 跨国无障碍交流',
            style: TextStyle(
              color: AppTheme.textSecondary.withOpacity(0.7),
              fontSize: 14,
            ),
          ),
          const SizedBox(height: 16),
          // 语言标签
          Wrap(
            spacing: 8,
            runSpacing: 8,
            alignment: WrapAlignment.center,
            children: [
              '中文', 'English', '日本語', '한국어', 'Français',
              'Deutsch', 'Español', 'Português', 'Русский',
              'العربية', 'ไทย', 'Tiếng Việt', 'Bahasa Indonesia',
            ].map((lang) {
              return Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decoration: BoxDecoration(
                  color: AppTheme.bgSurfaceDark,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(
                    color: AppTheme.borderGlow.withOpacity(0.4),
                  ),
                ),
                child: Text(
                  lang,
                  style: const TextStyle(
                    color: AppTheme.textSecondary,
                    fontSize: 12,
                  ),
                ),
              );
            }).toList(),
          ),
        ],
      ),
    );
  }
}

/// 帖子卡片
class _PostCard extends StatefulWidget {
  final _CommunityPost post;
  const _PostCard({required this.post});

  @override
  State<_PostCard> createState() => _PostCardState();
}

class _PostCardState extends State<_PostCard> {
  bool _isLiked = false;
  bool _showTranslation = false;
  String _selectedLang = 'en';

  @override
  Widget build(BuildContext context) {
    final post = widget.post;

    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
      decoration: BoxDecoration(
        color: AppTheme.bgCardDark,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: AppTheme.borderGlow.withOpacity(0.3),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 创作者信息
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 14, 16, 0),
            child: Row(
              children: [
                // 头像
                Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    gradient: AppTheme.gradientCyber,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Center(
                    child: Text(
                      post.creator.avatar,
                      style: const TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.w700,
                        fontSize: 16,
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Text(
                            post.creator.name,
                            style: const TextStyle(
                              color: AppTheme.textPrimary,
                              fontWeight: FontWeight.w600,
                              fontSize: 14,
                            ),
                          ),
                          const SizedBox(width: 4),
                          Text(
                            post.creator.country,
                            style: const TextStyle(fontSize: 14),
                          ),
                        ],
                      ),
                      Text(
                        '${post.creator.followers} 粉丝 · ${post.timeAgo}',
                        style: const TextStyle(
                          color: AppTheme.textHint,
                          fontSize: 11,
                        ),
                      ),
                    ],
                  ),
                ),
                // 关注按钮
                Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 14, vertical: 6),
                  decoration: BoxDecoration(
                    gradient: AppTheme.gradientNeon,
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: const Text(
                    '+ 关注',
                    style: TextStyle(
                      color: AppTheme.bgDeepDark,
                      fontSize: 11,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ],
            ),
          ),

          // 设计预览
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(12),
              child: Container(
                height: 200,
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    colors: [
                      AppTheme.secondaryNeonPurple.withOpacity(0.3),
                      AppTheme.primaryNeonGreen.withOpacity(0.1),
                    ],
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                  ),
                ),
                child: Stack(
                  children: [
                    Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(
                            Icons.auto_awesome,
                            size: 40,
                            color: AppTheme.secondaryNeonPurple
                                .withOpacity(0.6),
                          ),
                          const SizedBox(height: 8),
                          Text(
                            post.title,
                            style: const TextStyle(
                              color: AppTheme.textPrimary,
                              fontSize: 18,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                        ],
                      ),
                    ),
                    // 标签
                    Positioned(
                      bottom: 12,
                      left: 12,
                      child: Wrap(
                        spacing: 6,
                        children: post.tags.map((tag) {
                          return Container(
                            padding: const EdgeInsets.symmetric(
                                horizontal: 8, vertical: 3),
                            decoration: BoxDecoration(
                              color: AppTheme.bgDeepDark.withOpacity(0.7),
                              borderRadius: BorderRadius.circular(8),
                            ),
                            child: Text(
                              '#$tag',
                              style: const TextStyle(
                                color: AppTheme.primaryNeonGreen,
                                fontSize: 10,
                              ),
                            ),
                          );
                        }).toList(),
                      ),
                    ),
                    // Prompt 价格标签
                    if (post.promptPrice != null)
                      Positioned(
                        top: 12,
                        right: 12,
                        child: Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 10, vertical: 5),
                          decoration: BoxDecoration(
                            color: AppTheme.goldAccent.withOpacity(0.9),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Text(
                            'USDT ${post.promptPrice!.toStringAsFixed(2)}',
                            style: const TextStyle(
                              color: AppTheme.bgDeepDark,
                              fontSize: 12,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                        ),
                      ),
                  ],
                ),
              ),
            ),
          ),

          // 描述
          Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  post.description,
                  style: const TextStyle(
                    color: AppTheme.textSecondary,
                    fontSize: 13,
                    height: 1.5,
                  ),
                  maxLines: _showTranslation ? 10 : 2,
                  overflow: TextOverflow.ellipsis,
                ),
                const SizedBox(height: 8),
                // 翻译栏
                Row(
                  children: [
                    GestureDetector(
                      onTap: () =>
                          setState(() => _showTranslation = !_showTranslation),
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 8, vertical: 4),
                        decoration: BoxDecoration(
                          color: AppTheme.accentNeonCyan.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            const Icon(Icons.translate,
                                size: 12, color: AppTheme.accentNeonCyan),
                            const SizedBox(width: 4),
                            Text(
                              _showTranslation ? '收起翻译' : 'AI 翻译',
                              style: const TextStyle(
                                color: AppTheme.accentNeonCyan,
                                fontSize: 11,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    if (_showTranslation) ...[
                      const SizedBox(width: 8),
                      _LanguageChip(
                        lang: '中文',
                        code: 'zh',
                        selected: _selectedLang == 'zh',
                        onTap: () =>
                            setState(() => _selectedLang = 'zh'),
                      ),
                      const SizedBox(width: 4),
                      _LanguageChip(
                        lang: 'EN',
                        code: 'en',
                        selected: _selectedLang == 'en',
                        onTap: () =>
                            setState(() => _selectedLang = 'en'),
                      ),
                      const SizedBox(width: 4),
                      _LanguageChip(
                        lang: '日本語',
                        code: 'ja',
                        selected: _selectedLang == 'ja',
                        onTap: () =>
                            setState(() => _selectedLang = 'ja'),
                      ),
                    ],
                  ],
                ),
                if (_showTranslation)
                  Padding(
                    padding: const EdgeInsets.only(top: 8),
                    child: Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: AppTheme.accentNeonCyan.withOpacity(0.05),
                        borderRadius: BorderRadius.circular(10),
                        border: Border.all(
                          color: AppTheme.accentNeonCyan.withOpacity(0.15),
                        ),
                      ),
                      child: Text(
                        post.translations[_selectedLang] ?? post.description,
                        style: const TextStyle(
                          color: AppTheme.textSecondary,
                          fontSize: 13,
                          fontStyle: FontStyle.italic,
                          height: 1.5,
                        ),
                      ),
                    ),
                  ),
              ],
            ),
          ),

          // 交互栏
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            decoration: BoxDecoration(
              border: Border(
                top: BorderSide(
                  color: AppTheme.borderGlow.withOpacity(0.2),
                ),
              ),
            ),
            child: Row(
              children: [
                _InteractionButton(
                  icon: _isLiked ? Icons.favorite : Icons.favorite_border,
                  label: '${post.likes}',
                  color: _isLiked ? AppTheme.accentNeonPink : null,
                  onTap: () => setState(() {
                    _isLiked = !_isLiked;
                  }),
                ),
                const SizedBox(width: 20),
                _InteractionButton(
                  icon: Icons.chat_bubble_outline,
                  label: '${post.comments}',
                  onTap: () {},
                ),
                const SizedBox(width: 20),
                _InteractionButton(
                  icon: Icons.print,
                  label: '${post.prints} 打印',
                  onTap: () {},
                ),
                const Spacer(),
                _InteractionButton(
                  icon: Icons.share,
                  label: '分享',
                  onTap: () {},
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// Prompt 市场卡片
class _PromptMarketCard extends StatelessWidget {
  final _CommunityPost post;
  const _PromptMarketCard({required this.post});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppTheme.bgCardDark,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: AppTheme.goldAccent.withOpacity(0.3),
        ),
      ),
      child: Row(
        children: [
          // 预览图
          Container(
            width: 80,
            height: 80,
            decoration: BoxDecoration(
              gradient: AppTheme.gradientPurple,
              borderRadius: BorderRadius.circular(12),
            ),
            child: const Center(
              child: Icon(Icons.auto_awesome,
                  size: 30, color: Colors.white),
            ),
          ),
          const SizedBox(width: 14),
          // 信息
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  post.title,
                  style: const TextStyle(
                    color: AppTheme.textPrimary,
                    fontWeight: FontWeight.w600,
                    fontSize: 14,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'by ${post.creator.name} ${post.creator.country}',
                  style: const TextStyle(
                    color: AppTheme.textHint,
                    fontSize: 11,
                  ),
                ),
                const SizedBox(height: 6),
                Row(
                  children: [
                    const Icon(Icons.print,
                        size: 14, color: AppTheme.textHint),
                    const SizedBox(width: 4),
                    Text(
                      '${post.prints} 次打印',
                      style: const TextStyle(
                        color: AppTheme.textHint,
                        fontSize: 11,
                      ),
                    ),
                    const SizedBox(width: 12),
                    const Icon(Icons.attach_money,
                        size: 14, color: AppTheme.goldAccent),
                    Text(
                      '每次分成 ¥0.30',
                      style: const TextStyle(
                        color: AppTheme.goldAccent,
                        fontSize: 11,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          // 价格和购买
          Column(
            children: [
              Text(
                'USDT ${post.promptPrice!.toStringAsFixed(2)}',
                style: const TextStyle(
                  color: AppTheme.goldAccent,
                  fontSize: 18,
                  fontWeight: FontWeight.w800,
                ),
              ),
              const SizedBox(height: 8),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                decoration: BoxDecoration(
                  gradient: AppTheme.gradientGold,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Text(
                  '购买 Prompt',
                  style: TextStyle(
                    color: AppTheme.bgDeepDark,
                    fontSize: 12,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

/// 交互按钮
class _InteractionButton extends StatelessWidget {
  final IconData icon;
  final String label;
  final Color? color;
  final VoidCallback onTap;

  const _InteractionButton({
    required this.icon,
    required this.label,
    this.color,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            icon,
            size: 18,
            color: color ?? AppTheme.textHint,
          ),
          const SizedBox(width: 4),
          Text(
            label,
            style: TextStyle(
              color: color ?? AppTheme.textHint,
              fontSize: 12,
            ),
          ),
        ],
      ),
    );
  }
}

/// 语言选择芯片
class _LanguageChip extends StatelessWidget {
  final String lang;
  final String code;
  final bool selected;
  final VoidCallback onTap;

  const _LanguageChip({
    required this.lang,
    required this.code,
    required this.selected,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
        decoration: BoxDecoration(
          color: selected
              ? AppTheme.accentNeonCyan.withOpacity(0.15)
              : AppTheme.bgElevatedDark,
          borderRadius: BorderRadius.circular(8),
          border: selected
              ? Border.all(color: AppTheme.accentNeonCyan.withOpacity(0.4))
              : null,
        ),
        child: Text(
          lang,
          style: TextStyle(
            color: selected ? AppTheme.accentNeonCyan : AppTheme.textHint,
            fontSize: 11,
            fontWeight: selected ? FontWeight.w600 : FontWeight.w400,
          ),
        ),
      ),
    );
  }
}

/// 数据模型
class _Creator {
  final String name;
  final String avatar;
  final String country;
  final int followers;

  const _Creator(this.name, this.avatar, this.country, this.followers);
}

class _CommunityPost {
  final String id;
  final _Creator creator;
  final String title;
  final String description;
  final int likes;
  final int comments;
  final int prints;
  final double? promptPrice;
  final List<String> tags;
  final Map<String, String> translations;
  final DateTime timestamp;

  const _CommunityPost({
    required this.id,
    required this.creator,
    required this.title,
    required this.description,
    required this.likes,
    required this.comments,
    required this.prints,
    this.promptPrice,
    required this.tags,
    required this.translations,
    required this.timestamp,
  });

  String get timeAgo {
    final diff = DateTime.now().difference(timestamp);
    if (diff.inMinutes < 60) return '${diff.inMinutes} 分钟前';
    if (diff.inHours < 24) return '${diff.inHours} 小时前';
    return '${diff.inDays} 天前';
  }
}
